# fly.toml file generated for pokeindexcicd on 2022-12-31T12:46:39+02:00

app = "pokeindexcicd"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  app = "node app.js"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.script_checks]]
    command = "/app/health_check.sh"
    grace_period = "10s"
    interval = 10000
    restart_limit = 0
    timeout = 1000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "5s"
    restart_limit = 0
    timeout = "2s"
